# Here is docker compose file for nextcloud app
version: '3.8'

services:
  nextcloud-db:
    image: mariadb:10.5
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: FTC60zVSM6gE
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: khashayar
      MYSQL_PASSWORD: FTC60zVSM6gE

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: khashayar
      MYSQL_PASSWORD: FTC60zVSM6gE
    depends_on:
      - nextcloud-db

volumes:
  db_data:
  nextcloud_data:
